"use client";

import { useEffect, useState } from "react";
import { Bot, Check, LoaderCircle, Plus, RefreshCw, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import type { ModelConnection, ModelConnectionInput, ModelConnectionStatus, ModelConnectionValidation, ModelProtocol } from "@/lib/api/model-connections";
import { cn } from "@/lib/utils";
import { ProviderLogo } from "@/components/canvas/provider-logo";

const protocols: Array<{value:ModelProtocol; label:string; note:string}> = [
  {value:"openai",label:"OpenAI",note:"Official OpenAI API"}, {value:"anthropic",label:"Anthropic",note:"Official Claude API"}, {value:"openai-compatible",label:"OpenAI-compatible",note:"vLLM, LiteLLM, LM Studio and on-prem gateways"}, {value:"anthropic-compatible",label:"Anthropic-compatible",note:"Claude-compatible on-prem gateways"},
];
const empty: ModelConnectionInput={name:"",protocol:"openai",base_url:"https://api.openai.com/v1",api_key:"",text_model:"gpt-4.1-mini",vision_model:"gpt-4.1-mini",enabled:true};
const statusStyle: Record<ModelConnectionStatus,string>={ready:"text-emerald-700 bg-emerald-500/10 border-emerald-500/25",authentication_required:"text-amber-700 bg-amber-500/10 border-amber-500/25",incompatible:"text-rose-700 bg-rose-500/10 border-rose-500/25",unreachable:"text-rose-700 bg-rose-500/10 border-rose-500/25",blocked:"text-rose-700 bg-rose-500/10 border-rose-500/25"};

export function ModelConnectionConfiguration(){
 const [items,setItems]=useState<ModelConnection[]>([]),[open,setOpen]=useState(false),[form,setForm]=useState<ModelConnectionInput>(empty),[validation,setValidation]=useState<ModelConnectionValidation|null>(null),[busy,setBusy]=useState<string|null>(null),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null);
 const load=async()=>{try{const r=await fetch("/api/configuration/model-connections",{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.detail??"Could not load model connections");setItems(b.items)}catch(e){setError(e instanceof Error?e.message:"Could not load model connections")}};
 useEffect(()=>{void load()},[]);
 const set=<K extends keyof ModelConnectionInput>(key:K,value:ModelConnectionInput[K])=>{setForm(v=>({...v,[key]:value}));setValidation(null)};
 const validate=async()=>{setBusy("new");setError(null);try{const r=await fetch("/api/configuration/model-connections/validate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const b=await r.json();if(!r.ok)throw new Error(b.detail??"Validation failed");setValidation(b)}catch(e){setError(e instanceof Error?e.message:"Validation failed")}finally{setBusy(null)}};
 const save=async()=>{setSaving(true);try{const r=await fetch("/api/configuration/model-connections",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const b=await r.json();if(!r.ok)throw new Error(b.detail??"Could not save");setItems(v=>[b,...v]);setOpen(false);setForm(empty);setValidation(null)}catch(e){setError(e instanceof Error?e.message:"Could not save")}finally{setSaving(false)}};
 const update=async(id:string,body:Record<string,unknown>)=>{setBusy(id);try{const r=await fetch(`/api/configuration/model-connections/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const b=await r.json();if(!r.ok)throw new Error(b.detail??"Could not update");setItems(v=>v.map(i=>i.id===id?b:i))}catch(e){setError(e instanceof Error?e.message:"Could not update")}finally{setBusy(null)}};
 const revalidate=async(id:string)=>{setBusy(id);try{const r=await fetch(`/api/configuration/model-connections/${id}/validate`,{method:"POST"});const b=await r.json();if(!r.ok)throw new Error(b.detail??"Validation failed");setItems(v=>v.map(i=>i.id===id?b:i))}catch(e){setError(e instanceof Error?e.message:"Validation failed")}finally{setBusy(null)}};
 const remove=async(id:string)=>{if(!window.confirm("Remove this model connection? Stored credentials will be deleted."))return;setBusy(id);try{const r=await fetch(`/api/configuration/model-connections/${id}`,{method:"DELETE"});if(!r.ok)throw new Error("Could not remove connection");setItems(v=>v.filter(i=>i.id!==id))}catch(e){setError(e instanceof Error?e.message:"Could not remove")}finally{setBusy(null)}};
 return <section className="overflow-hidden rounded-2xl border border-border bg-card shadow-[0_14px_40px_rgba(31,20,76,0.05)]"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-border px-6 py-5"><div><p className="font-mono text-[10px] tracking-[.14em] text-primary uppercase">Language intelligence</p><h2 className="mt-1 text-base font-bold tracking-[-.02em]">LLM & vision connections</h2><p className="mt-1 text-sm text-muted-foreground">Connect OpenAI, Anthropic, or a compatible cloud, local, and on-prem endpoint.</p></div><Button onClick={()=>setOpen(true)}><Plus/> Add provider</Button></div>{error?<div role="alert" className="mx-6 mt-4 rounded-xl border border-destructive/25 bg-destructive/8 px-3 py-2 text-sm text-destructive">{error}</div>:null}<div className="divide-y divide-border">{items.length===0?<div className="flex items-center gap-3 px-6 py-8 text-sm text-muted-foreground"><Bot className="size-5 text-primary"/>No LLM or VLM providers connected yet.</div>:items.map(item=>{const s=item.last_validation?.status??"unreachable";return <div key={item.id} className={cn("flex flex-wrap items-start justify-between gap-4 px-6 py-5",!item.enabled&&"opacity-55")}><div className="min-w-0"><div className="flex items-center gap-2.5"><span className="flex size-9 items-center justify-center rounded-xl border border-border bg-muted"><ProviderGlyph protocol={item.protocol}/></span><h3 className="font-semibold">{item.name}</h3><span className={cn("rounded-full border px-2 py-0.5 text-[11px] font-semibold",statusStyle[s])}>{s.replaceAll("_"," ")}</span></div><p className="mt-2 truncate font-mono text-xs text-muted-foreground">{item.base_url}</p><p className="mt-2 text-xs text-muted-foreground">Text: {item.text_model??"not set"} · Vision: {item.vision_model??"not set"} · {item.has_api_key?"API key stored":"No API key"}</p>{item.last_validation?.detail?<p className="mt-2 text-xs text-muted-foreground">{item.last_validation.detail}</p>:null}</div><div className="flex items-center gap-1"><Switch checked={item.enabled} disabled={busy===item.id} onCheckedChange={v=>void update(item.id,{enabled:v})}/><Button size="icon-sm" variant="ghost" disabled={busy===item.id} onClick={()=>void revalidate(item.id)} aria-label={`Revalidate ${item.name}`}>{busy===item.id?<LoaderCircle className="animate-spin"/>:<RefreshCw/>}</Button><Button size="icon-sm" variant="ghost" className="hover:text-destructive" disabled={busy===item.id} onClick={()=>void remove(item.id)} aria-label={`Remove ${item.name}`}><Trash2/></Button></div></div>})}</div><ConnectionDialog open={open} onOpenChange={setOpen} form={form} set={set} validation={validation} probing={busy==="new"} saving={saving} validate={validate} save={save}/></section>
}
function ProviderGlyph({protocol}:{protocol:ModelProtocol}){const openai=protocol.startsWith("openai");return <ProviderLogo provider={openai ? "openai" : "anthropic"} size={openai ? 22 : 18}/>}
function ConnectionDialog({open,onOpenChange,form,set,validation,probing,saving,validate,save}:{open:boolean;onOpenChange:(v:boolean)=>void;form:ModelConnectionInput;set:<K extends keyof ModelConnectionInput>(k:K,v:ModelConnectionInput[K])=>void;validation:ModelConnectionValidation|null;probing:boolean;saving:boolean;validate:()=>void;save:()=>void}){return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[calc(100vh-2rem)] overflow-y-auto rounded-2xl sm:max-w-xl"><DialogHeader><DialogTitle>Connect an LLM or VLM provider</DialogTitle><DialogDescription>Credentials are encrypted. Use compatible endpoints for vLLM, LiteLLM, LM Studio, or your internal gateway.</DialogDescription></DialogHeader><div className="grid gap-4"><Field label="Connection name"><Input value={form.name} onChange={e=>set("name",e.target.value)} placeholder="Production OpenAI"/></Field><Field label="Provider protocol"><select className="h-10 w-full rounded-lg border border-input bg-transparent px-2.5 text-sm" value={form.protocol} onChange={e=>set("protocol",e.target.value as ModelProtocol)}>{protocols.map(p=><option key={p.value} value={p.value}>{p.label} — {p.note}</option>)}</select></Field><Field label="Base URL"><Input value={form.base_url} onChange={e=>set("base_url",e.target.value)} placeholder="https://api.openai.com/v1"/></Field><Field label="API key"><Input type="password" value={form.api_key} onChange={e=>set("api_key",e.target.value)} placeholder="Stored encrypted" autoComplete="new-password"/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Default text model"><Input value={form.text_model} onChange={e=>set("text_model",e.target.value)} placeholder="gpt-4.1-mini"/></Field><Field label="Default vision model"><Input value={form.vision_model} onChange={e=>set("vision_model",e.target.value)} placeholder="gpt-4.1-mini"/></Field></div><label className="flex items-center justify-between rounded-xl bg-muted/50 px-3 py-2.5 text-sm font-medium">Enable after saving<Switch checked={form.enabled} onCheckedChange={v=>set("enabled",v)}/></label>{validation?<div className={cn("rounded-xl border p-3 text-sm",statusStyle[validation.status])}>{validation.detail}{validation.discovered_models.length?<p className="mt-2 font-mono text-[11px]">{validation.discovered_models.slice(0,8).join(" · ")}</p>:null}</div>:null}</div><DialogFooter><Button variant="ghost" onClick={()=>onOpenChange(false)}>Cancel</Button><Button variant="outline" onClick={validate} disabled={probing||!form.base_url}>{probing?<LoaderCircle className="animate-spin"/>:<RefreshCw/>} Validate</Button><Button onClick={save} disabled={saving||validation?.status!=="ready"}>{saving?<LoaderCircle className="animate-spin"/>:<Check/>} Save provider</Button></DialogFooter></DialogContent></Dialog>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="grid gap-1.5"><Label className="text-xs font-semibold">{label}</Label>{children}</label>}
