import { Activity, CheckCircle2, FileText, KeyRound, ShieldAlert, ShieldCheck, UsersRound } from "lucide-react";

import type { ApiKey, ApiKeyUsageItem, ApiKeyUsageSummary } from "@/lib/api/account";

type AdminApiKeysTabProps = { keys: ApiKey[]; usageByKey: Record<string, ApiKeyUsageSummary> };

function formatDate(value: string | null) {
  return value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Never";
}

function relativeDate(value: string) {
  const minutes = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 60_000));
  if (minutes < 2) return "just now";
  if (minutes < 60) return `${minutes}m ago`;
  if (minutes < 1_440) return `${Math.floor(minutes / 60)}h ago`;
  return `${Math.floor(minutes / 1_440)}d ago`;
}

export function AdminApiKeysTab({ keys, usageByKey }: AdminApiKeysTabProps) {
  const requests = keys.reduce((sum, key) => sum + key.request_count, 0);
  const documents = keys.reduce((sum, key) => sum + key.document_count, 0);
  const failures = keys.reduce((sum, key) => sum + key.failed_requests, 0);
  const successes = keys.reduce((sum, key) => sum + key.successful_requests, 0);
  const activeKeys = keys.filter((key) => key.is_active).length;
  const developers = new Set(keys.map((key) => key.owner_id)).size;
  const successRate = requests ? Math.round((successes / requests) * 100) : 100;
  const busiest = [...keys].sort((a, b) => b.request_count - a.request_count).slice(0, 5);
  const maxRequests = Math.max(...busiest.map((key) => key.request_count), 1);
  const events = keys.flatMap((key) => (usageByKey[key.id]?.timeline ?? []).map((event) => ({ event, key }))).sort((a, b) => Date.parse(b.event.created_at) - Date.parse(a.event.created_at)).slice(0, 12);
  return <div className="mt-8 space-y-6">
    <section className="relative overflow-hidden rounded-2xl border border-border bg-card p-6 shadow-[0_18px_45px_-32px_rgba(35,24,89,0.45)]"><div className="absolute inset-y-0 right-0 w-2/5 bg-[radial-gradient(circle_at_90%_10%,color-mix(in_srgb,var(--primary)_18%,transparent),transparent_65%)]" /><div className="relative flex flex-wrap items-end justify-between gap-5"><div><p className="font-mono text-[10px] tracking-[0.18em] text-primary uppercase">Integration control room</p><h2 className="mt-2 text-2xl font-extrabold tracking-[-0.035em] text-foreground">API key operations</h2><p className="mt-2 max-w-xl text-sm text-muted-foreground">See who created each integration, the pipeline it calls, document volume, delivery health, and recent requests.</p></div><div className="flex items-center gap-3 rounded-xl border border-border bg-background/70 px-4 py-3 backdrop-blur-sm"><div className="grid size-10 place-items-center rounded-full" style={{ background: `conic-gradient(var(--primary) ${successRate}%, color-mix(in srgb, var(--destructive) 18%, transparent) 0)` }}><span className="grid size-7 place-items-center rounded-full bg-background text-[10px] font-bold">{successRate}%</span></div><div><p className="text-sm font-bold">Request health</p><p className="text-xs text-muted-foreground">{successes} successful · {failures} failed</p></div></div></div></section>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={KeyRound} label="Active keys" value={`${activeKeys}`} note={`${keys.length} issued total`} tone="primary" /><Metric icon={Activity} label="API requests" value={requests.toLocaleString()} note={`${successRate}% request health`} tone="blue" /><Metric icon={FileText} label="Documents received" value={documents.toLocaleString()} note="Across API submissions" tone="emerald" /><Metric icon={UsersRound} label="Integration owners" value={`${developers}`} note={`${failures} delivery errors`} tone={failures ? "rose" : "primary"} /></div>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.2fr)_minmax(300px,0.8fr)]"><section className="overflow-hidden rounded-2xl border border-border bg-card"><div className="flex items-center justify-between border-b border-border px-6 py-5"><div><h3 className="font-bold">Keys and pipeline access</h3><p className="mt-1 text-sm text-muted-foreground">Owner identity, allowed pipelines, and operational state.</p></div><KeyRound className="size-5 text-primary" /></div>{keys.length === 0 ? <EmptyState /> : <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-muted/35 font-mono text-[10px] tracking-[0.12em] text-muted-foreground uppercase"><tr><th className="px-6 py-3 font-medium">Integration owner</th><th className="px-4 py-3 font-medium">Key / scope</th><th className="px-4 py-3 font-medium">Pipeline access</th><th className="px-4 py-3 font-medium">Usage</th><th className="px-6 py-3 font-medium">Last activity</th></tr></thead><tbody className="divide-y divide-border">{keys.map((key) => <KeyRow key={key.id} item={key} />)}</tbody></table></div>}</section><section className="rounded-2xl border border-border bg-card p-6"><div className="flex items-center justify-between"><div><h3 className="font-bold">Most active keys</h3><p className="mt-1 text-sm text-muted-foreground">Request volume by integration.</p></div><ShieldCheck className="size-5 text-primary" /></div>{busiest.length ? <div className="mt-7 space-y-5">{busiest.map((key) => <div key={key.id}><div className="flex items-center justify-between gap-3 text-sm"><span className="truncate font-medium">{key.name}</span><span className="font-mono text-xs text-muted-foreground">{key.request_count.toLocaleString()}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${Math.max(4, (key.request_count / maxRequests) * 100)}%` }} /></div><p className="mt-1 text-xs text-muted-foreground">{key.owner_email ?? "Unknown owner"} · {key.document_count} docs</p></div>)}</div> : <EmptyState />}</section></div>
    <section className="overflow-hidden rounded-2xl border border-border bg-card"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-border px-6 py-5"><div><h3 className="font-bold">Request timeline</h3><p className="mt-1 text-sm text-muted-foreground">Latest API calls, including pipeline, result, document count, and status.</p></div><span className="rounded-full bg-muted px-3 py-1 font-mono text-[10px] tracking-[0.1em] text-muted-foreground uppercase">Last {events.length} events</span></div>{events.length === 0 ? <EmptyState /> : <div className="overflow-x-auto"><table className="w-full min-w-[880px] text-left text-sm"><thead className="bg-muted/35 font-mono text-[10px] tracking-[0.12em] text-muted-foreground uppercase"><tr><th className="px-6 py-3 font-medium">When</th><th className="px-4 py-3 font-medium">Owner / key</th><th className="px-4 py-3 font-medium">Pipeline</th><th className="px-4 py-3 font-medium">Request</th><th className="px-4 py-3 font-medium">Documents</th><th className="px-6 py-3 font-medium">Outcome</th></tr></thead><tbody className="divide-y divide-border">{events.map(({ key, event }) => <TimelineRow key={event.id} item={event} apiKey={key} />)}</tbody></table></div>}</section>
  </div>;
}

function Metric({ icon: Icon, label, value, note, tone }: { icon: typeof KeyRound; label: string; value: string; note: string; tone: "primary" | "blue" | "emerald" | "rose" }) { const tones = { primary: "bg-primary/10 text-primary", blue: "bg-blue-500/10 text-blue-600", emerald: "bg-emerald-500/10 text-emerald-600", rose: "bg-rose-500/10 text-rose-600" }; return <div className="rounded-xl border border-border bg-card px-5 py-4"><div className="flex items-center justify-between"><p className="font-mono text-[10px] tracking-[0.12em] text-muted-foreground uppercase">{label}</p><span className={`grid size-8 place-items-center rounded-lg ${tones[tone]}`}><Icon className="size-4" /></span></div><p className="mt-3 text-2xl font-extrabold tracking-tight">{value}</p><p className="mt-1 text-xs text-muted-foreground">{note}</p></div>; }

function KeyRow({ item }: { item: ApiKey }) { return <tr className="align-top hover:bg-muted/20"><td className="px-6 py-4"><p className="font-medium">{item.owner_email ?? "Unknown owner"}</p><p className="mt-1 font-mono text-[10px] text-muted-foreground">{item.owner_id}</p></td><td className="px-4 py-4"><p className="font-medium">{item.name}</p><p className="mt-1 font-mono text-[11px] text-muted-foreground">{item.key_prefix}••••••••</p><span className={item.is_active ? "mt-2 inline-flex rounded-full bg-emerald-500/10 px-2 py-0.5 text-[10px] font-semibold text-emerald-700" : "mt-2 inline-flex rounded-full bg-muted px-2 py-0.5 text-[10px] font-semibold text-muted-foreground"}>{item.is_active ? "ACTIVE" : "REVOKED"}</span></td><td className="px-4 py-4"><p className="max-w-[210px] truncate font-medium" title={item.allowed_pipeline_names.join(", ")}>{item.allowed_pipeline_names.length ? item.allowed_pipeline_names.join(", ") : "All owner pipelines"}</p><p className="mt-1 text-xs text-muted-foreground">{item.allowed_pipeline_names.length ? `${item.allowed_pipeline_names.length} explicitly allowed` : "Unrestricted within owner scope"}</p></td><td className="px-4 py-4"><p>{item.request_count.toLocaleString()} requests</p><p className="mt-1 text-xs text-muted-foreground">{item.document_count.toLocaleString()} documents · <span className={item.failed_requests ? "text-destructive" : "text-emerald-700"}>{item.failed_requests} errors</span></p></td><td className="px-6 py-4"><p>{formatDate(item.last_used_at)}</p><p className="mt-1 text-xs text-muted-foreground">Created {formatDate(item.created_at)}</p></td></tr>; }

function TimelineRow({ item, apiKey }: { item: ApiKeyUsageItem; apiKey: ApiKey }) { const success = item.outcome === "success"; return <tr className="hover:bg-muted/20"><td className="px-6 py-3"><p className="font-medium">{relativeDate(item.created_at)}</p><p className="mt-1 text-xs text-muted-foreground">{formatDate(item.created_at)}</p></td><td className="px-4 py-3"><p className="font-medium">{apiKey.owner_email ?? "Unknown owner"}</p><p className="mt-1 text-xs text-muted-foreground">{apiKey.name}</p></td><td className="px-4 py-3"><p className="font-medium">{item.pipeline_name ?? "Pipeline unavailable"}</p><p className="mt-1 font-mono text-[10px] text-muted-foreground">{item.pipeline_id ?? "—"}</p></td><td className="px-4 py-3"><p className="font-mono text-xs">{item.method} {item.endpoint}</p><p className="mt-1 text-xs text-muted-foreground">HTTP {item.status_code}</p></td><td className="px-4 py-3">{item.document_count || "—"}</td><td className="px-6 py-3"><span className={success ? "inline-flex items-center gap-1.5 rounded-full bg-emerald-500/10 px-2.5 py-1 text-xs font-semibold text-emerald-700" : "inline-flex items-center gap-1.5 rounded-full bg-destructive/10 px-2.5 py-1 text-xs font-semibold text-destructive"}>{success ? <CheckCircle2 className="size-3.5" /> : <ShieldAlert className="size-3.5" />}{success ? "Accepted" : item.error_code ?? "Error"}</span></td></tr>; }

function EmptyState() { return <div className="grid min-h-36 place-items-center px-6 text-center text-sm text-muted-foreground">No API-key activity has been recorded yet.</div>; }
